### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by RestOp** [Zingle/smtp2http#1]
git clone git@github.com:Zingle/smtp2http.git
Cloning into 'smtp2http'...
The authenticity of host 'github.com (140.82.118.3)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,140.82.118.3' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by richRemer** [comment]
This does not appear to be relevant to the repository.
